package com.ventouxlabs.bascule.ble.decoders

import com.ventouxlabs.bascule.ble.session.DecodeEvent
import com.ventouxlabs.bascule.ble.session.DiscoveredServices
import com.ventouxlabs.bascule.ble.session.GattOp
import com.ventouxlabs.bascule.ble.session.ScaleCredential
import java.util.UUID
import kotlin.time.Duration

/**
 * Connection-oriented decoder contract (ADR-001), revised in Phase 2 per ADR-007
 * — see docs/prp/02-interface-revision.md.
 *
 * The change of substance vs. 00-design.md §2.6: `initSequence(): List<GattOp>`
 * modelled the handshake as a fixed, stateless list returned once. The real
 * handshake is stateful and conditional — register only when no credential is
 * stored for this scale, otherwise send Consent directly, and fall back to
 * re-registration if a stored credential is rejected. A list cannot express a
 * branch, so the handshake is driven event by event through
 * [beginHandshake]/[onHandshakeEvent].
 *
 * Implementations remain per-session stateful and perform no I/O, so every
 * failure edge in 00-design.md §2.3 stays reproducible in a JVM unit test.
 */
interface ScaleDecoder {
    val id: String

    /** Dispatch and discovery check. */
    val requiredServices: Set<UUID>

    /** Characteristics the session subscribes to once the handshake completes. */
    val measurementCharacteristics: Set<UUID>

    /** Advertisement-level dispatch only — matching, never decoding. */
    fun matches(advertisedName: String?, serviceUuids: Set<UUID>): Boolean

    /**
     * First directive of the handshake, chosen from what is already known about
     * this scale. Called once, after discovery.
     */
    fun beginHandshake(discovered: DiscoveredServices, context: HandshakeContext): HandshakeDirective

    /**
     * Advances the handshake in response to an event decoded from the User
     * Control Point. Returns [HandshakeDirective.Wait] for anything that does
     * not move it forward.
     */
    fun onHandshakeEvent(event: DecodeEvent): HandshakeDirective

    /** Called for every inbound frame. Never throws (00-design.md §8.9). */
    fun onNotification(characteristic: UUID, value: ByteArray): DecodeEvent

    /**
     * Releases anything the decoder is still holding for correlation, at
     * end-of-session or post-emission idle. Returns null when nothing is held.
     *
     * This exists because a Body Composition Measurement carries no timestamp
     * and no user ID of its own (ADR-007) and must be paired with its Weight
     * Measurement before either is a complete reading. The decoder buffers the
     * weight frame; if the body-composition frame never arrives, the session
     * calls [flush] and gets a weight-only reading rather than losing it.
     */
    fun flush(): DecodeEvent?

    /** Best-effort clean shutdown ops; failures here never fail a session. */
    fun teardownSequence(): List<GattOp>
}

/**
 * What the session knows going into a handshake: the stored credential for this
 * scale if there is one, and a freshly generated consent code to register with
 * if there is not.
 *
 * The consent code is generated by the session, not the decoder, because it is
 * credential material that needs a cryptographic RNG and encrypted storage —
 * both of which are I/O the decoder is deliberately kept free of.
 */
data class HandshakeContext(
    val storedCredential: ScaleCredential?,
    val freshConsentCode: Int,
)

sealed interface HandshakeDirective {
    /** Execute this op and wait for the acknowledging indication. */
    data class Send(val op: GattOp, val expectAckWithin: Duration) : HandshakeDirective

    /** Nothing to do with this event; keep waiting for the outstanding ack. */
    data object Wait : HandshakeDirective

    /**
     * The scale has consented. [credential] is non-null when this session
     * registered a new user and the session must persist the mapping.
     */
    data class Complete(val credential: ScaleCredential?) : HandshakeDirective

    data class Abort(val reason: String) : HandshakeDirective
}
